version: "3"
services:

  # gin-mongo app
  gin-mongo:
    image: gin-mongo:latest
    restart: always
    ports:
      - 8085:8085
    environment: 
      - GIN_MONGO_FILE_PATH=/opt/configuration/config.yaml
    volumes:
      - ./configuration:/opt/configuration

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.68.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./configuration/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - jaeger-all-in-one

  krakend:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:watch
    volumes:
      - ./configuration:/etc/krakend
    ports:
      - "8090:8090"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    networks:
      - keycloak-dev-network

  #KEYCLOAK
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    command: start-dev
    volumes:
      - keycloak_data:/etc/keycloak/keycloak_data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    networks:
      - keycloak-dev-network

volumes:
  keycloak_data:
      driver: local

networks:
  keycloak-dev-network:
    driver: bridge