version: "3"
services:
  krakend:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:watch
    volumes:
      - ./configuration:/etc/krakend
    ports:
      - "8090:8090"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.yaml"]
    networks:
      - keycloak-dev-network

networks:
  keycloak-dev-network:
    driver: bridge