log:
  level: -1
  enablejson: false
config:
  database:
    connectionstring: "mongodb://192.168.3.109:27017"
  ginrouter:
    router: "0.0.0.0:8085"
  observability:
    serviceName: "gin-mongo"
    endpoint: "192.168.3.109:4317"
    enable: true